### ISSUE TITLE
How to interpret psm.tsv output file

### ISSUE THREAD

**Issue by maimuell** [chhh/MSFragger-GUI#16]
Hi Dmitry 

I am using MSfragger to look for previously unrecognised peptide modifications in my samples.  
For this, the interactive delta-mass distribution plot has proven to be very useful. So thank you for that!

However, I could use some help in interpreting the psm.tsv file MSfragger is giving me:

- What does the Delta Mass adjustment involve?
- What's the difference between Assigned and Observed Modifications?
- What's the mass tolerance when referring to unimod annotated modifications? Is there a way to modify that?

Many thanks for answering my questions
Maik

**Comment by prvst** [comment]
Hey @maimuell; 

The PSM table and most of the downstream processing occurring after running MSFragger comes from another program called [Philosopher](https://prvst.github.io/philosopher/), it's a command line tool that allows you to do post-processing and filtering including the modification mapping. 

> What does the Delta Mass adjustment involve?

Philosopher calculates the mass deviation for the Mass Difference in each pepXML file based on the 0 bin mass difference. In order to keep track of things, it reports both the 'raw' (the exact mass reported on the pepXML files) and the adjusted one.

> What's the difference between Assigned and Observed Modifications?

This is terminology that I came up to distinguish the modifications that you **assign** on the search parameters (i.e. fixed / variable mods) and the **observed** modifications found by the MSFragger open search (i.e. based on the Mass Difference).

> What's the mass tolerance when referring to https://github.com/prvst/philosopher annotated modifications? Is there a way to modify that?

I believe you are asking what's the tolerance when mapping the Mass Difference values to UniMOD entries right ? if so, that's 10 ppm and it's not adjustable by the user.

If you have further questions regarding Philosopher, you can post them on [Philosopher's github page ](https://github.com/prvst/philosopher)

**Comment by maimuell** [comment]
OK and thanks for answering my questions!
