### ISSUE TITLE
Questions regarding decoys

### ISSUE THREAD

**Issue by ziningchen** [chhh/MSFragger-GUI#2]
# Describe the problem

* **I'm submitting a:**
  - [ ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [x] question

Hello,

I just had a question regarding the decoy database. Since MS Fragger doesn't generate decoys, I created reverse decoys of each sequence and appended them after the original database. Is there a way to specify in MS Fragger that the bottom half of my database are decoys, or does MS Fragger automatically recognizes this?

Thanks!

**Comment by chhh** [comment]
Hi @ziningchen ,
If you run [FragPipe](https://github.com/chhh/FragPipe) (previously MSFragger-GUI), which is a GUI application, there is a tab for Sequence Database. The written instructions on that tab will guide you through the process of creating a database with decoys using Philosopher step by step. 

On this tab you specify the path to your FASTA file. There is also a button to try auto-detect common identifiers of decoy sequences, it will tell you what it has found. Most typically it's "rev_" prefix to the protein id string.

MSFragger itself does not care if a protein is a decoy or not, it just performs the search and spits outs the matches. Only peptide/protein validation tools (Peptide Prophet, Protein Prophet) will consider that information. The prefix that you've specified on the Sequence DB tab will be used to run these tools with proper configuration, so that they knew how to tell decoys from forwards.

Hope it helps.

Best,
Dmitry
