### ISSUE TITLE
quantification of assigned/observed modifications

### ISSUE THREAD

**Issue by talpa25** [chhh/MSFragger-GUI#38]
Dear developers,

i have now the first dataset analysed with MSFragger. My primary aim for using MSFragger was the open search option. There were a lot of modifcations assigned/observed. My first question is for the difference between them. Am i right, that the assigned modifications are those I've selected to search for and the observed ones are the ones coming from the open search?
Whe I look into the modifications.tsv and i compare the mass bins between assigned and observed and there are for Oxidation (15.9926) i get ~ 1400 for assigned and 170 for observed. Does this mean that the main modification is as selected a Methionin oxidation and 170 modifications are non methionin oxidations? How do i see the residues in an overview that are observed for oxdidation modification?
I assume that for IAA modifications it's similar? 
[modifications.zip](https://github.com/chhh/MSFragger-GUI/files/1674101/modifications.zip)

Is there a quantified overview of the observed modifications including the modified residues? Or can i calculate them somehow from the protein.fas or peptide.tsv?
[proteins.zip](https://github.com/chhh/MSFragger-GUI/files/1674116/proteins.zip)
[psm.zip](https://github.com/chhh/MSFragger-GUI/files/1674117/psm.zip)

Actually, i want to use the enlighted "dark" modifications by MSFragger to enhance the PSM in Crosslink-PSM programms like Kojak. 

Thank you in advance

Best
Roman

**Comment by andytyk** [comment]
Hi Roman,

Modifications that are specified as variable modifications will not be marked with a mass difference in the MSFragger output.  I'd imagine that the ~1400 "assigned" refer to these modifications while the ~170 "observed" are those discovered through open searching (oxidation on non-methionine residues).  I'm not perfectly clear on this myself so I'll refer you to @prvst who maintains the Philosopher project and can provide an authoritative clarification.

MSFragger can be used to quickly identify crosslinks in open search.  Just use a tolerance large enough to encompass your crosslinked fragments.  That should quickly nominate the most common cross linked species (by mass) in your sample.  You can then use these masses to search in a more targeted fashion using MSFragger or some other tool.

**Comment by prvst** [comment]
@talpa25 

Your assumption is correct. When you ask [Philosopher](https://github.com/prvst/philosopher) to process and filter your data set on an _open search_ mode, the program separates the modifications defined by you during the peptide spectrum matching (i.e. assigned), from the modifications that were discovered (i.e. observed via mass difference or delta mass). Although some times you find cases where a certain assigned modification is found only via mass diference, there is no pre-defined cause for that.

In order to get a better understanding of how your peptides are modified you might try some tools like PTMProphet, the tool you provide you with a localization score for the modifications.

Finally, right now  [Philosopher](https://github.com/prvst/philosopher) doesn't provide a differential quantification for modified and unmodified peptides in your data set, but that's on our road map. But you definitively can add quantitative data to your searches, I suggest you to take a look at the  [Philosopher](https://github.com/prvst/philosopher) project and give it a try outside the GUI, you will find more functionalities including precursor and label quantification.

**Comment by talpa25** [comment]
@andytyk I'm not 100% sure whether i got your advice right. When i talk about crosslinks i talk about peptide - crosslinking compound - peptide crosslinks (e.g. K-BS3-K). When I do an open search with MSFragger it would give me high molecular modifications, right. But how would MSFragger decide which peptide is the modification (including the mass shift by the cross linker) and which peptide is the target? Would that be just random? And if so, is there a chance to assign the XL-peptides by looking for identifications pairs (peptide1 = target, XL + peptide 2 = modification & peptide 2 = target, XL + peptide 1 = modification) with the same mass?

**Comment by talpa25** [comment]
thx @prvst for confirming my assumption. I'll have a deeper look into PTMProphet and Philosopher.

best
