### ISSUE TITLE
The link to MSfragger in Umich tech transfer is for the older version of MS fragger

### ISSUE THREAD

**Issue by Dmorgen** [chhh/MSFragger-GUI#48]
unless I'm looking at the wrong place?

Thanks!
David.

**Comment by andytyk** [comment]
Hi David,

We've had this issue for a few days and have reached out to the Tech Transfer office to get this fixed with their upstream provider.  In the meantime, if you can e-mail me with the old copy of MSFragger, I can provide you with the updated one.

We will soon be doing auto-updates using the GUI so there'll be no need to go through Tech Transfer in the future for updates.

Best,
Andy

**Comment by Dmorgen** [comment]
Thanks!

which file would you need exactly?

Cheers,
David.

**Comment by Dmorgen** [comment]
Hi Andy,

Thanks for the swift reply!
Which file would you need exactly?

Cheers,
David.

**Comment by Dmorgen** [comment]
can you send me your email please? I will send you a link to the files I currently have.
